LionSkyNot/LionSkyNot/Areas/Admin/Models/Trainers/AddTrainerFormModel.cs
using System.ComponentModel.DataAnnotations;

using LionSkyNot.Views.ViewModels.Trainers;

using static LionSkyNot.Data.DataConstants.Trainer;


namespace LionSkyNot.Models
{
    public class AddTrainerFormModel
    {

        [MaxLength(NameMaxLength)]
        [MinLength(NameMinLength)]
        [Required]
        public string FullName { get; set; }

        [Url]
        [Required]
        public string ImageUrl { get; set; }

        [MaxLength(DescriptionMaxLength)]
        [MinLength(DescriptionMinLength)]
        [Required]
        public string Description { get; set; }

        [Range(YearOfExperienceMin, YearOfExperienceMax)]
        public int YearOfExperience { get; set; }

        public DateTime BirthDate { get; set; }

        [Range(WeightMin, WeightMax)]
        public float Weight { get; set; }

        [Range(HeightMin, HeightMax)]
        public float Height { get; set; }

        public int CategorieId { get; set; }

        public IEnumerable<CategorieViewModel>? Categorie { get; set; }

    }
}

LionSkyNot/LionSkyNot/Areas/Admin/Models/Trainers/AddTrainerFromAdminFormModel.cs
using System.ComponentModel.DataAnnotations;

using LionSkyNot.Views.ViewModels.Trainers;

using static LionSkyNot.Data.DataConstants.Trainer;


namespace LionSkyNot.Models.Trainers
{
    public class AddTrainerFromAdminFormModel
    {
        
        [Required]
        public string Username { get; set; }

        [MaxLength(NameMaxLength)]
        [MinLength(NameMinLength)]
        [Required]
        public string FullName { get; set; }

        [Url]
        [Required]
        public string ImageUrl { get; set; }

        [MaxLength(DescriptionMaxLength)]
        [MinLength(DescriptionMinLength)]
        [Required]
        public string Description { get; set; }

        [Range(YearOfExperienceMin, YearOfExperienceMax)]
        public int YearOfExperience { get; set; }

        public DateTime BirthDate { get; set; }

        [Range(WeightMin, WeightMax)]
        public float Weight { get; set; }

        [Range(HeightMin, HeightMax)]
        public float Height { get; set; }

        public int CategorieId { get; set; }

        public IEnumerable<CategorieViewModel>? Categorie { get; set; }

    }
}

LionSkyNot/LionSkyNot/Areas/Admin/Models/Trainers/TrainerFormModelForAdmin.cs
namespace LionSkyNot.Models.Trainers
{
    public class TrainerFormModelForAdmin
    {

        public int Id { get; set; }

        public string FullName { get; set; }

    }
}

LionSkyNot/LionSkyNot/Models/Trainers/TrainerSort.cs
namespace LionSkyNot.Models.Trainers
{
    public enum TrainerSort
    {

        YearOfExperience = 0,
        Youngest = 1,
        Oldest = 2

    }
}

LionSkyNot/LionSkyNot/Areas/Admin/Controllers/TrainerController.cs
using LionSkyNot.Controllers;

using LionSkyNot.Models.Trainers;

using LionSkyNot.Services.Trainers;
using LionSkyNot.Services.Users;
using LionSkyNot.Views.ViewModels.Trainers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using static LionSkyNot.Areas.Admin.AdminConstants;


namespace LionSkyNot.Areas.Admin.Controllers
{

    [Area(AreaName)]
    [Authorize(Roles = AdminRole)]
    public class TrainerController : BaseController
    {

        private ITrainerService trainerService;
        private IUserService userService;

        public TrainerController(ITrainerService trainerService, IUserService userService)
        {
            this.trainerService = trainerService;
            this.userService = userService;
        }



        public IActionResult Successfull()
        {
            return View();
        }


        public IActionResult ShowCandidateTrainers(IEnumerable<TrainerCandidateViewModel> trainerCandidateModel)
        {
            var candidateTrainers = this.trainerService.GetAllTrainerCandidates();

            return View(candidateTrainers);
        }


        public IActionResult ShowTrainers(IEnumerable<TrainerFormModelForAdmin> trainerModel)
        {

            trainerModel = this.trainerService.GetAllTrainersForAdmin();

            return View(trainerModel);

        }


        public async Task<IActionResult> AddTrainerCandidate(int id)
        {

            var currentCandidate = this.trainerService.GetCandidateTrainerById(id);

            if (currentCandidate == null)
            {
                return BadRequest();
            }

            await this.trainerService.AddCandidateAsync(currentCandidate);


            return View("Successfull");
        }


        public IActionResult AddTrainer()
        {
            return View(new AddTrainerFromAdminFormModel
            {
                Categorie = this.trainerService.GetAllCategories()
            });
        }


        [HttpPost]
        public async Task<IActionResult> AddTrainer(AddTrainerFromAdminFormModel trainerModel)
        {
            var currentUser = this.userService.GetUser(trainerModel.Username);
            trainerModel.Categorie = this.trainerService.GetAllCategories();

            if (currentUser == null)
            {
                ModelState.AddModelError("notFindUser", "The user is not exists");
            }

            if (!ModelState.IsValid)
            {
                return View(trainerModel);
            }

            if (this.trainerService.IsTrainer(currentUser.Id))
            {
                ModelState.AddModelError("userIsTrainer", "The user is already trainer");

            }

            if (!ModelState.IsValid)
            {
                return View(trainerModel);
            }

            var existsUserId = currentUser.Id;


            await this.trainerService.CreateAsync(
                                        trainerModel.FullName,
                                        trainerModel.YearOfExperience,
                                        trainerModel.ImageUrl,
                                        trainerModel.Height,
                                        trainerModel.Weight,
                                        trainerModel.BirthDate,
                                        trainerModel.CategorieId,
                                        trainerModel.Description,
                                        existsUserId,
                                        false);

            return RedirectToAction("Successfull");

        }


        public async Task<IActionResult> DeleteTrainer(int id)
        {

            var isDeleted = await this.trainerService.DeleteAsync(id);

            if (!isDeleted)
            {
                return BadRequest();
            }



            return View("Successfull");

        }

    }
}

LionSkyNot/LionSkyNot/Controllers/TrainerController.cs
using LionSkyNot.Infrastructure;

using LionSkyNot.Models;

using LionSkyNot.Services.Classes;
using LionSkyNot.Services.Trainers;

using LionSkyNot.Views.ViewModels.Classes;
using LionSkyNot.Views.ViewModels.Trainers;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace LionSkyNot.Controllers
{
    public class TrainerController : BaseController
    {

        private ITrainerService trainerService;
        private IClassService classService;


        public TrainerController(ITrainerService trainerService, IClassService classService)
        {
            this.trainerService = trainerService;
            this.classService = classService;
        }


        public IActionResult Index(string searchTerm)
        {

            if (!string.IsNullOrWhiteSpace(searchTerm) && !string.IsNullOrEmpty(searchTerm))
            {
                var searchTrainers = trainerService.SearchTrainerByName(searchTerm);

                var allTrainersViewModel = new AllTrainersViewModel()
                {
                    Trainers = searchTrainers
                };

                return View("TrainerSearch", allTrainersViewModel);

            }

            return View();
        }


        [Authorize]
        public IActionResult BecomeTrainer()
        => View(new AddTrainerFormModel
        {
            Categorie = this.trainerService.GetAllCategories()
        });


        [HttpPost]
        [Authorize]
        public async Task<IActionResult> BecomeTrainer(AddTrainerFormModel trainerModel)
        {
            trainerModel.Categorie = this.trainerService.GetAllCategories();
            var currentUserId = ClaimsPrincipalExtensions.GetId(this.User);
            var allTrainersUserId = this.trainerService.GetAllTrainersUserId(false);
            var allCandidateTrainersUserId = this.trainerService.GetAllTrainersUserId(true);


            if (allTrainersUserId.Any(a => a.UserId == currentUserId))
            {
                ModelState.AddModelError("error", "The current user is already a trainer!");
            }

            if (allCandidateTrainersUserId.Any(a => a.UserId == currentUserId))
            {
                ModelState.AddModelError("error", "The current user is candidate already for trainer!");
            }

            if (!ModelState.IsValid)
            {
                return View(trainerModel);
            }

            await this.trainerService.CreateAsync(
                                        trainerModel.FullName,
                                        trainerModel.YearOfExperience,
                                        trainerModel.ImageUrl,
                                        trainerModel.Height,
                                        trainerModel.Weight,
                                        trainerModel.BirthDate,
                                        trainerModel.CategorieId,
                                        trainerModel.Description,
                                        currentUserId,
                                        true);


            return RedirectToAction("CandidatureSuccess");
        }


        public IActionResult CandidatureSuccess()
        => View();


        [Authorize]
        public IActionResult TrainerClasses(IEnumerable<ClassTrainerViewModel> classModel)
        {
            var currentUserId = ClaimsPrincipalExtensions.GetId(this.User);
            int currentTrainerId = this.trainerService.GetTrainerId(currentUserId);

            classModel = this.classService.GetAllTrainerClasses(currentTrainerId);

            return View(classModel);
        }


        public IActionResult YogaTrainers(AllTrainersViewModel trainersModel)
        {

            trainersModel.Trainers = this.trainerService.GetAllTrainersByCategory("Yoga");

            return View(trainersModel);
        }


        public IActionResult BoxTrainers(AllTrainersViewModel trainersModel)
        {

            trainersModel.Trainers = this.trainerService.GetAllTrainersByCategory("Box");

            return View(trainersModel);
        }


        public IActionResult MmaTrainers(AllTrainersViewModel trainersModel)
        {

            trainersModel.Trainers = this.trainerService.GetAllTrainersByCategory("MMA");

            return View(trainersModel);
        }


        public IActionResult FitnessTrainers(AllTrainersViewModel trainersModel)
        {

            trainersModel.Trainers = this.trainerService.GetAllTrainersByCategory("Fitness");

            return View(trainersModel);
        }


        public IActionResult WrestlerTrainers(AllTrainersViewModel trainersModel)
        {
            trainersModel.Trainers = this.trainerService.GetAllTrainersByCategory("Wrestling");

            return View(trainersModel);
        }


        public IActionResult AthleticTrainers(AllTrainersViewModel trainersModel)
        {
            trainersModel.Trainers = this.trainerService.GetAllTrainersByCategory("Athletic");

            return View(trainersModel);
        }
    }
}

LionSkyNot/LionSkyNot/Areas/Admin/Views/Trainer/AddTrainer.cshtml
@model AddTrainerFromAdminFormModel

<link rel="stylesheet" href="~/css/form.css" asp-append-version="true" />

@{
    ViewData["Title"] = "Add Trainer";
}


<div>
    <img class="center" src="https://media.istockphoto.com/photos/male-personal-trainer-helping-sportswoman-to-do-exercises-with-at-picture-id972833328?k=20&m=972833328&s=612x612&w=0&h=LtGaklhIxyJbMkxEKDNWzGXgX-zmONE2-llVRDrv17c=">
</div>
<br />
<br />

<div class="row">
    <div class="offset-md-3 col-md-6 col-sm-12 ">


        <form method="post">
            <div class="text-danger">@Html.ValidationMessage("notFindUser")</div>
            <div class="text-danger">@Html.ValidationMessage("userIsTrainer")</div>

            <div class="form-group">
                <label asp-for="Username">Username</label>
                <input asp-for="Username" type="text" value="" class="form-control"> </input>
                <span asp-validation-for="Username" class="small text-danger"> </span>
            </div>
            <div class="form-group">
                <label asp-for="FullName">Full name</label>
                <input asp-for="FullName" type="text" class="form-control">
                <span asp-validation-for="FullName" class="small text-danger"> </span>
            </div>

            <div class="form-group">
                <label asp-for="Description">Description</label>
                <input asp-for="Description" type="text" class="form-control">
                <span asp-validation-for="Description" class="small text-danger"> </span>
            </div>

            <div class="form-group">
                <label asp-for="YearOfExperience">Year of experience</label>
                <input asp-for="YearOfExperience" type="text" value="" class="form-control"> </input>
                <span asp-validation-for="YearOfExperience" class="small text-danger"> </span>
            </div>

            <div class="form-group">
                <label asp-for="BirthDate">BirthDate</label>
                <input asp-for="BirthDate" type="date" value="" class="form-control" id="input3">
                <span asp-validation-for="BirthDate" class="small text-danger"> </span>
            </div>


            <div class="form-group">
                <label asp-for="Weight">Weight</label>
                <input asp-for="Weight" type="text" value="" class="form-control" id="input3">
                <span asp-validation-for="Weight" class="small text-danger"> </span>
            </div>

            <div class="form-group">
                <label asp-for="Height">Height</label>
                <input asp-for="Height" type="text" value="" class="form-control" id="input3">
                <span asp-validation-for="Height" class="small text-danger"> </span>
            </div>

            <div class="form-group">
                <label asp-for="ImageUrl">Image Url</label>
                <input asp-for="ImageUrl" type="text" class="form-control" id="input3">
                <span asp-validation-for="ImageUrl" class="small text-danger"> </span>
            </div>
            <br />
            <br />
            <div class="form-group">
                <label asp-for="CategorieId">Choose category</label>
                <select asp-for="CategorieId" class="form-control form-control-sm">

                    @foreach (var current in Model.Categorie)
                    {
                        <option value="@current.Id">@current.Name</option>
                    }
                </select>
            </div>

            <br />
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>
</div>

@section Scripts {
<partial name="_ValidationScriptsPartial" />
}

LionSkyNot/LionSkyNot/Areas/Admin/Views/Trainer/ShowCandidateTrainers.cshtml
 @model IEnumerable<TrainerCandidateViewModel>

<link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />

@{
    ViewData["Title"] = "All Candidates";
}


<div class="container">
    <div class="row">
        <div class="col-12">
            <table class="table table-image">
                <thead>
                    <tr>
                        <th scope="col">Image</th>
                        <th scope="col">Trainer Name</th>
                        <th scope="col">BirthDate</th>
                        <th scope="col">YearOfExperience</th>
                        <th scope="col">Category</th>
                        <th scope="col">Add</th>
                        <th scope="col">Remove</th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var currentTrainer in Model)
                    {
                            <tr>
                                <td class="w-25">
                                    <img src="@currentTrainer.ImageUrl" class="img-fluid img-thumbnail" alt="Sheep">
                                </td>
                                <td>@currentTrainer.FullName</td>
                                <td>@currentTrainer.BirthDate.ToString("dd-MM-yyyy")</td>
                                <td>@currentTrainer.YearOfExperience</td>
                                <td>@currentTrainer.Category</td>
                                <td><a asp-controller="Trainer" asp-action="AddTrainerCandidate" asp-route-id="@currentTrainer.Id" class="btn btn-success">Add Trainer</a></td>
                                <td><a asp-controller="Trainer" asp-action="DeleteTrainer" asp-route-id="@currentTrainer.Id" class="btn btn-danger">Remove</a></td>
                            </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

LionSkyNot/LionSkyNot/Areas/Admin/Views/Trainer/ShowTrainers.cshtml
@model IEnumerable<TrainerFormModelForAdmin>

<link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />

@{
    ViewData["Title"] = "All Trainers";
}


<div class="row">

    @if (Model.Any())
    {
        <table class="table table-dark">
            <thead>
                <tr>
                    <th scope="col">Trainer Name</th>
                    <th scope="col">Delete</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var trainer in Model)
                {

                    <tr>
                        <td>@trainer.FullName</td>
                        <td><a asp-controller="Trainer" asp-action="DeleteTrainer" asp-route-id="@trainer.Id" class="btn btn-danger">Delete Trainer</a></td>
                    </tr>
                }

            </tbody>
        </table>

    }
    else
    {
        <h1> Don't have trainers yet , try soon !</h1>
    }

LionSkyNot/LionSkyNot/Areas/Admin/Views/Trainer/Successfull.cshtml
<link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />


@{
    ViewData["Title"] = "Success";
}

<div class="alert alert-success">
  <strong>Success!</strong>
</div>