LionSkyNot/LionSkyNot/Controllers/ClassController.cs
using LionSkyNot.Infrastructure;

using LionSkyNot.Services.Classes;

using LionSkyNot.Views.ViewModels.Classes;

using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Mvc;

using Microsoft.Extensions.Caching.Memory;


namespace LionSkyNot.Controllers
{
    public class ClassController : BaseController
    {

        private IClassService classService;
        private IMemoryCache cache;

        public ClassController(IClassService classService, IMemoryCache cache)
        {
            this.classService = classService;
            this.cache = cache;
        }


        public IActionResult Index(AllClassViewModel allClassModel)
        {

            const string allCountOfClassesKeyCache = "AllCountOfClassesKeyCache";

            allClassModel = this.cache.Get<AllClassViewModel>(allCountOfClassesKeyCache);

            if (allClassModel == null)
            {
                allClassModel = this.classService.GetCountOfAllClasses();

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allCountOfClassesKeyCache, allClassModel);
            }


            return View(allClassModel);
        }


        [Authorize]
        public IActionResult ViewAllFitnessClass()
        {

            const string allFitnessClassesKeyCache = "AllFitnessClassesKeyCache";

            var allFitnessClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allFitnessClassesKeyCache);

            if (allFitnessClasses == null)
            {
                allFitnessClasses = this.classService.GetAllClassesByCategorieName("Fitness");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allFitnessClassesKeyCache, allFitnessClasses);
            }


            return View(allFitnessClasses);
        }


        [Authorize]
        public IActionResult ViewAllYogaClass()
        {

            const string allYogaClassesKeyCache = "AllYogaClassesKeyCache";

            var allYogaClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allYogaClassesKeyCache);

            if (allYogaClasses == null)
            {
                allYogaClasses = this.classService.GetAllClassesByCategorieName("Yoga");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allYogaClassesKeyCache, allYogaClasses);
            }


            return View(allYogaClasses);
        }


        [Authorize]
        public IActionResult ViewAllMmaClass()
        {

            const string allMmaClassesKeyCache = "AllMmaClassesKeyCache";

            var allMmaClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allMmaClassesKeyCache);

            if (allMmaClasses == null)
            {
                allMmaClasses = this.classService.GetAllClassesByCategorieName("Mma");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allMmaClassesKeyCache, allMmaClasses);
            }


            return View(allMmaClasses);
        }


        [Authorize]
        public IActionResult ViewAllBoxClass()
        {

            const string allBoxClassesKeyCache = "AllBoxClassesKeyCache";

            var allBoxClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allBoxClassesKeyCache);

            if (allBoxClasses == null)
            {
                allBoxClasses = this.classService.GetAllClassesByCategorieName("Box");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allBoxClassesKeyCache, allBoxClasses);
            }
            return View(allBoxClasses);
        }


        [Authorize]
        public IActionResult ViewAllWrestlingClass()
        {

            const string allWrestlingClassesKeyCache = "AllWrestlingClassesKeyCache";

            var allWrestlingClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allWrestlingClassesKeyCache);

            if (allWrestlingClasses == null)
            {
                allWrestlingClasses = this.classService.GetAllClassesByCategorieName("Wrestling");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allWrestlingClassesKeyCache, allWrestlingClasses);
            }
            return View(allWrestlingClasses);
        }


        [Authorize]
        public IActionResult ViewAllAthleticClass()
        {

            const string allAthleticClassesKeyCache = "AllAthleticClassesKeyCache";

            var allAthleticClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allAthleticClassesKeyCache);

            if (allAthleticClasses == null)
            {
                allAthleticClasses = this.classService.GetAllClassesByCategorieName("Athletic");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allAthleticClassesKeyCache, allAthleticClasses);
            }
            return View(allAthleticClasses);
        }


        [Authorize]
        public IActionResult ViewDetails(string id)
        {

            const string viewDetailsKeyCache = "viewDetailsKeyCache";

            var viewDetails = this.cache.Get<ClassDetailsViewModel>(viewDetailsKeyCache);

            if (viewDetails == null)
            {
                viewDetails = this.classService.GetClassForDetails(id);

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(viewDetailsKeyCache, viewDetails);
            }
            return View(viewDetails);
        }


        [Authorize]
        public async Task<IActionResult> Join(string id)
        {

            var currentUserId = ClaimsPrincipalExtensions.GetId(this.User);

            if (this.classService.CheckFreePlace(id))
            {
                return View("ToMuchPeopleInClass");
            }

            var result = await this.classService.AddUserToClassAsync(currentUserId, id);

            if (!result)
            {
                return View("UserAlreadyInClass");
            }
            return View("SuccessJoin");
        }


        public IActionResult ViewUserClasses()
        {
            var currentUserId = ClaimsPrincipalExtensions.GetId(this.User);

            return View(this.classService.GetUserClasses(currentUserId));
        }


        public async Task<IActionResult> RemoveFromClassUser(string id)
        {
            var currentUserId = ClaimsPrincipalExtensions.GetId(this.User);

            var result = await this.classService.RemovingClassFromUserAsync(currentUserId, id);

            if (!result)
            {
                return BadRequest();
            }
            return View("SuccessRemoveClassUser");
        }
    }
}

LionSkyNot/LionSkyNot/Controllers/GymController.cs
using Microsoft.AspNetCore.Mvc;

namespace LionSkyNot.Controllers
{
    public class GymController : BaseController
    {

        public IActionResult Index()
        => View();

    }
}

LionSkyNot/LionSkyNot/Controllers/RecipeController.cs
using LionSkyNot.Services.Recipes;

using LionSkyNot.Views.ViewModels.Recipes;

using Microsoft.AspNetCore.Mvc;


namespace LionSkyNot.Controllers
{
    public class RecipeController : BaseController
    {

        private IRecipeService recipeService;

        public RecipeController(IRecipeService recipeService)
        {
            this.recipeService = recipeService;
        }



        public IActionResult Index(IEnumerable<RecipeViewModel> recipeViewModel)
        => View(this.recipeService.GetAll());

    }
}

LionSkyNot/LionSkyNot/Controllers/ShopController.cs
using LionSkyNot.Services.Products;

using LionSkyNot.Views.ViewModels.Products;

using Microsoft.AspNetCore.Mvc;


namespace LionSkyNot.Controllers
{
    public class ShopController : BaseController
    {

        private IProductService productService;

        public ShopController(IProductService productService)
        {
            this.productService = productService;
        }



        public IActionResult Index([FromQuery] AllProductsViewModel query)
        {

            var allProductViewModel = new AllProductsViewModel()
            {
                Brands = this.productService.GetAllBrandProduct().Select(x => x.Name),
                Types = this.productService.GetAllTypesProduct().Select(x => x.Name)
            };

            if (!string.IsNullOrWhiteSpace(query.Brand) &&
                !string.IsNullOrEmpty(query.Brand) &&
                !string.IsNullOrWhiteSpace(query.Type) &&
                !string.IsNullOrEmpty(query.Type) &&
                !string.IsNullOrWhiteSpace(query.SortedBy.ToString()) &&
                !string.IsNullOrEmpty(query.SortedBy.ToString()))
            {

                var products = this.productService.GetProductsByBrandAndType(query.Type, query.Brand);

                products = query.SortedBy switch
                {
                    SortedProductViewModel.SortedByPrice => products = this.productService.SortedByPrice(products),
                    SortedProductViewModel.SortedByPriceDescending => products = this.productService.SortedByPriceDescending(products),
                    SortedProductViewModel.SortedByName => products = this.productService.SortedByName(products),
                    SortedProductViewModel.SortedByMostBuys => products = this.productService.SortedByMostBuys(products),
                    _ => products = this.productService.SortedByName(products)
                };


                var finalProducts = this.productService.GetFinalProductsSelected(products);


                return View("Result", finalProducts);
            }

            return View(allProductViewModel);
        }


        public IActionResult ViewDetails(int id)
        => View(this.productService.GetProductForDetails(id));


        public IActionResult AllProducts()
         => View(this.productService.ShowAllProducts());


        public IActionResult MostBuyedProducts()
         => View(this.productService.ShowMostBuyedProducts());


        public IActionResult SaleProducts()
        => View(this.productService.GetAllProductsOnPromotion());

    }
}

LionSkyNot/LionSkyNot/Views/Shared/NotFound.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>404 HTML Tempalte by Colorlib</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,900" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="css/PageNotFound.css" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
			</div>
			<h2>404 - Page not found</h2>
			<p>The page you are looking for might have been removed had its name changed or is temporarily unavailable.</p>
			<a href="#">Go To Homepage</a>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

s

LionSkyNot/LionSkyNot/Views/Shared/_Footer.cshtml
<footer class="bg-dark text-center text-white mt-auto">
    <!-- Grid container -->
    <div class="container p-4">
        <!-- Section: Social media -->
        <!-- Section: Text -->
        <!-- Section: Links -->
        <section class="">
            <!--Grid row-->
            <div class="row">
                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Most atractive fitness website</h5>
                    <p style="color:white">This site is created only for education . All products , recipes , trainers has been taken only for education.</p>
                </div>
                <!--Grid column-->
                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Fitness things</h5>

                    <ul class="list-unstyled mb-0">
                        <li>
                            <a asp-area="" asp-controller="Class" asp-action="Index" class="text-white">Classes</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Trainer" asp-action="Index" class="text-white">Trainers</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Exercise" asp-action="Index" class="text-white">Exercises</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Calculator" asp-action="Index" class="text-white">Calculator</a>
                        </li>
                    </ul>
                </div>
                <!--Grid column-->
                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Magazine / Health</h5>

                    <ul class="list-unstyled mb-0">
                        <li>
                            <a asp-area="" asp-controller="Shop" asp-action="Index" class="text-white">Shop</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Recipe" asp-action="Index" class="text-white">Recipes</a>
                        </li>
                        <li>
                            <a asp-area="" asp-controller="Contact" asp-action="Index" class="text-white">Contact</a>
                        </li>
                    </ul>
                </div>

                @if (!User.Identity.IsAuthenticated)
                {
                     <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
                    <h5 class="text-uppercase">Free Login / Register</h5>

                    <ul class="list-unstyled mb-0">
                        <li>
                            <a asp-area="Identity" asp-page="/Account/Login"  class="btn btn-primary">LogIn</a>
                        </li>
                        <li>
                            <br />
                        </li>
                        <li>
                            <a asp-area="Identity" asp-page="/Account/Register"  class="btn btn-danger">Register</a>
                        </li>

                    </ul>
                </div>
                }
         
                <!--Grid column-->
            </div>

            <!--Grid column-->
            <!--Grid column-->
            <!--Grid column-->
    </div>
    <!--Grid row-->
    </section>
    <!-- Section: Links -->
    </div>

</footer>

LionSkyNot/LionSkyNot/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LionSkyNot</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LionSkyNot.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body class="d-flex flex-column min-vh-100">
    <header>

        @Html.Partial("_Menu")

    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @Html.Partial("_Footer")


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>

LionSkyNot/LionSkyNot/Views/Shared/_Menu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 ">
    <div class="container-fluid">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lion Sky</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Class" asp-action="Index">Classes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Exercise" asp-action="Index">Exercises</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Shop" asp-action="Index">Shop</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Recipe" asp-action="Index">Recipes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Calculator" asp-action="Index">Calculator</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Trainer" asp-action="Index">Trainers</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-white" asp-area="" asp-controller="Gym" asp-action="Index">Gym Offers</a>
                </li>


            </ul>
            <ul class="navbar-nav flex-grow-1 navbar-right">

                @if (this.User.Identity.IsAuthenticated)
                {
                    <li class="right">
                        <a class="nav-link text-white" asp-area="" asp-controller="WishList" asp-action="Index"><span class="glyphicon glyphicon-shopping-cart"></span> Cart</a>
                    </li>
                }

                @if (User.Identity.IsAuthenticated && (User.IsInRole("Administrator") || User.IsInRole("Moderator")))
                {
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin Panel</a>
                    </li>
                }
            </ul>
            <partial name="_LoginPartial" />
        </div>
    </div>
</nav>