LionSkyNot/LionSkyNot/Areas/Admin/Controllers/ShopController.cs
using LionSkyNot.Controllers;

using LionSkyNot.Models.Products;

using LionSkyNot.Services.Products;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using static LionSkyNot.Areas.Admin.AdminConstants;


namespace LionSkyNot.Areas.Admin.Controllers
{
    [Area(AreaName)]
    public class ShopController : BaseController
    {

        private IProductService productService;

        public ShopController(IProductService productService)
        {
            this.productService = productService;
        }



        [Authorize(Roles = ModeratorAndAdminRole)]
        public IActionResult AddProduct()
        {
            return View(new AddProductFormModel()
            {
                Type = this.productService.GetAllTypesProduct(),
                Brand = this.productService.GetAllBrandProduct()
            });

        }


        [Authorize(Roles = ModeratorAndAdminRole)]
        [HttpPost]
        public async Task<IActionResult> AddProduct(AddProductFormModel productModel)
        {

            if (!productService.IsHaveType(productModel.TypeId))
            {
                this.ModelState.AddModelError(nameof(productModel.TypeId), "Don't make some hack tries!");
            }

            if (!productService.IsHaveBrand(productModel.BrandId))
            {
                this.ModelState.AddModelError(nameof(productModel.BrandId), "Don't make some hack tries!");
            }

            if (!ModelState.IsValid)
            {
                productModel.Type = this.productService.GetAllTypesProduct();
                productModel.Brand = this.productService.GetAllBrandProduct();

                return View(productModel);
            }

            await this.productService.CreateProductAsync(
                 productModel.Name,
                 productModel.Price,
                 productModel.InStock,
                 productModel.Description,
                 productModel.ImageUrl,
                 productModel.TypeId,
                 productModel.BrandId);

            return RedirectToAction("Successfull");
        }


        [Authorize(Roles = ModeratorAndAdminRole)]
        public async Task<IActionResult> AddProductsInStock()
        {
            var isDone = await this.productService.UpdateInStockCountOfProductsAsync();

            if (!isDone)
            {
                return RedirectToAction("NotSuccess");
            }


            return View();
        }


        [Authorize(Roles = AdminRole)]
        public IActionResult Successfull()
        {
            return View();
        }


        [Authorize(Roles = AdminRole)]
        public IActionResult NotSuccess()
        {
            return View();
        }


        [Authorize(Roles = AdminRole)]
        public IActionResult ShowProducts(IEnumerable<ProductServiceModel> serviceModel)
        {

            serviceModel = this.productService.GetAllProductsForAdmin();

            return View(serviceModel);
        }


        [Authorize(Roles = AdminRole)]
        public IActionResult EditProduct(int id)
        {

            var currentProduct = this.productService.GetProductById(id);

            if (currentProduct == null)
            {
                return BadRequest();
            }

            return View(new EditProductFormModel()
            {
                ImageUrl = currentProduct.ImageUrl,
                Price = currentProduct.Price,
                Name = currentProduct.Name,
            });
        }


        [Authorize(Roles = AdminRole)]
        [HttpPost]
        public async Task<IActionResult> EditProduct(EditProductFormModel productModel, int id)
        {

            if (!ModelState.IsValid)
            {
                return View(productModel);
            }

            var isEditted = await this.productService.EditProductAsync(
                                                              id,
                                                              productModel.ImageUrl,
                                                              productModel.Name,
                                                              productModel.Price,
                                                              productModel.PromotionPercentage);

            if (!isEditted)
            {
                return BadRequest();
            }

            return RedirectToAction("Successfull");
        }


        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            var isDeleted = await this.productService.DeleteProductAsync(id);

            if (!isDeleted)
            {
                return BadRequest();
            }

            return View("Successfull");
        }

    }
}

LionSkyNot/LionSkyNot/Controllers/ShopController.cs
using LionSkyNot.Services.Products;

using LionSkyNot.Views.ViewModels.Products;

using Microsoft.AspNetCore.Mvc;


namespace LionSkyNot.Controllers
{
    public class ShopController : BaseController
    {

        private IProductService productService;

        public ShopController(IProductService productService)
        {
            this.productService = productService;
        }



        public IActionResult Index([FromQuery] AllProductsViewModel query)
        {

            var allProductViewModel = new AllProductsViewModel()
            {
                Brands = this.productService.GetAllBrandProduct().Select(x => x.Name),
                Types = this.productService.GetAllTypesProduct().Select(x => x.Name)
            };

            if (!string.IsNullOrWhiteSpace(query.Brand) &&
                !string.IsNullOrEmpty(query.Brand) &&
                !string.IsNullOrWhiteSpace(query.Type) &&
                !string.IsNullOrEmpty(query.Type) &&
                !string.IsNullOrWhiteSpace(query.SortedBy.ToString()) &&
                !string.IsNullOrEmpty(query.SortedBy.ToString()))
            {

                var products = this.productService.GetProductsByBrandAndType(query.Type, query.Brand);

                products = query.SortedBy switch
                {
                    SortedProductViewModel.SortedByPrice => products = this.productService.SortedByPrice(products),
                    SortedProductViewModel.SortedByPriceDescending => products = this.productService.SortedByPriceDescending(products),
                    SortedProductViewModel.SortedByName => products = this.productService.SortedByName(products),
                    SortedProductViewModel.SortedByMostBuys => products = this.productService.SortedByMostBuys(products),
                    _ => products = this.productService.SortedByName(products)
                };


                var finalProducts = this.productService.GetFinalProductsSelected(products);


                return View("Result", finalProducts);
            }

            return View(allProductViewModel);
        }


        public IActionResult ViewDetails(int id)
        => View(this.productService.GetProductForDetails(id));


        public IActionResult AllProducts()
         => View(this.productService.ShowAllProducts());


        public IActionResult MostBuyedProducts()
         => View(this.productService.ShowMostBuyedProducts());


        public IActionResult SaleProducts()
        => View(this.productService.GetAllProductsOnPromotion());

    }
}

LionSkyNot/LionSkyNot/Controllers/WishListController.cs
using LionSkyNot.Models.Products;

using LionSkyNot.Services.Products;
using LionSkyNot.Services.WishLists;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace LionSkyNot.Controllers
{

    [Authorize]
    public class WishListController : BaseController
    {
        private IProductService productService;
        private IWishListService wishListService;

        public WishListController(
                                  IProductService productService,
                                  IWishListService wishListService)
        {
            this.productService = productService;
            this.wishListService = wishListService;
        }


        public IActionResult Index()
        {
            var user = Infrastructure.ClaimsPrincipalExtensions.GetId(this.User);


            var tuple = this.wishListService.GetProductsOfUser(user);

            if (tuple.Item1 == false)
            {
                return View("NotAddedProducts");
            }

            var currentProducts = tuple.Item2;

            if (currentProducts.Products.Count() == 0)
            {
                return View("NotAddedProducts");
            }


            return View(currentProducts);
        }


        public async Task<IActionResult> AddToWishList(int id)
        {
            var user = Infrastructure.ClaimsPrincipalExtensions.GetId(this.User);

            var currentProduct = this.productService.TakeProduct(id);
            var isAdded = await this.wishListService.AddAsync(currentProduct, user);

            if (!isAdded)
            {
                return BadRequest();
            }

            return View("SuccessAddToWishList");
        }


        public async Task<IActionResult> RemoveProduct(int id)
        {
            var user = Infrastructure.ClaimsPrincipalExtensions.GetId(this.User);

            var isRemoved = await this.wishListService.RemoveProductAsync(id, user);

            if (!isRemoved)
            {
                return BadRequest();
            };

            return View("SuccessRemoveProduct");
        }


        public IActionResult Payment()
        => View();


        [HttpPost]
        public IActionResult Payment(PaymentFormModel paymentModel)
        {

            if (!ModelState.IsValid)
            {
                return View(paymentModel);
            }


            return RedirectToAction("BuyProducts");
        }

        public IActionResult BuyProducts()
        {

            var user = Infrastructure.ClaimsPrincipalExtensions.GetId(this.User);

            var tuple = this.wishListService.BuyProducts(user);

            if (tuple.Item1 == false && tuple.Item2 == null)
            {
                return BadRequest();
            }

            if (tuple.Item1 == false)
            {
                return View("BuyedProducts", tuple.Item2);
            }


            return View("SuccessBuyedAll", tuple.Item2);

        }
    }
}

LionSkyNot/LionSkyNot/Views/Shop/AllProducts.cshtml
@model IEnumerable<ProductListViewModel>

 @{
    ViewData["Title"] = "Products";
}

<partial name="_ShopPartial" model="@Model"/>

LionSkyNot/LionSkyNot/Views/Shop/Bcaa.cshtml
namespace LionSkyNot.Views.Shop
{
    public class Bcaa
    {
    }
}

LionSkyNot/LionSkyNot/Views/Shop/Creatine.cshtml
namespace LionSkyNot.Views.Shop
{
    public class Creatine
    {
    }
}

LionSkyNot/LionSkyNot/Views/Shop/LCarnitine.cshtml
namespace LionSkyNot.Views.Shop
{
    public class L_Carnitine
    {
    }
}

LionSkyNot/LionSkyNot/Views/Shop/MostBuyedProducts.cshtml
@model IEnumerable<ProductListViewModel>

 @{
    ViewData["Title"] = "Most buyed products";
}

<partial name="_ShopPartial" model="@Model"/>

LionSkyNot/LionSkyNot/Views/Shop/Protein.cshtml
namespace LionSkyNot.Views.Shop
{
    public class Protein
    {
    }
}

LionSkyNot/LionSkyNot/Views/Shop/Result.cshtml
@model IEnumerable<ProductListViewModel>

 @{
    ViewData["Title"] = "Search result";
}


<link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />


<div class="container pb-5 mt-n2 mt-md-n3">
    <div class="row">
        <div class="col-xl-9 col-md-8">

            @if (!Model.Any())
            {
                <div class="container">
                    <div class="jumbotron">
                        <h1>Don't have in the moment products</h1>
                        <p>
                            Please try soon , we will add it in stock!
                        </p>
                    </div>
                </div>
            }


            @foreach (var product in Model)
            {

                <!-- Item-->
                <div class="d-sm-flex justify-content-between my-4">
                    <div class="media d-block d-sm-flex text-center text-sm-left">
                        <img src="@product.ImageUrl" width="240" height="240">
                        <div class="media-body pt-3">
                            <h3 class="product-card-title font-weight-semibold border-0 pb-0"> <a asp-controller="Shop" asp-action="ViewDetails" asp-route-id="@product.Id">@product.Name</a></h3>
                            <div class="font-size-sm">Brand: @product.Brand</div>
                            <div class="font-size-sm">Type: @product.Type</div>

                            @if (@product.InStock == 0)
                            {
                                <div class="font-size-sm">Soon in stock</div>
                            }
                            else
                            {
                                <div class="font-size-sm">In Stock: @product.InStock</div>
                            }

                            @if (product.IsOnPromotion)
                            {
                                <div class="font-size-lg text-danger pt-2"><strike>Old Price: @String.Format(product.Price % 1 == 0 ? "{0:0}" : "{0:0.00}", product.Price) £ </strike></div>
                                <div class="font-size-lg text-warning pt-2"> New Price: @String.Format(product.PriceOnPromotion % 1 == 0 ? "{0:0}" : "{0:0.00}", product.PriceOnPromotion) £</div>
                            }
                            else
                            {
                                <div class="font-size-lg text-danger pt-2">Price: @String.Format(product.Price % 1 == 0 ? "{0:0}" : "{0:0.00}", product.Price) £</div>
                            }


                        </div>
                    </div>
                    <div class="pt-2 pt-sm-0 pl-sm-3 mx-auto mx-sm-0 text-center text-sm-left" style="max-width: 10rem;">

                        <br />
                        <br />
                        <a asp-controller="Shop" asp-action="ViewDetails" asp-route-id="@product.Id" class="btn btn-warning">View Details</a>


                        <br />
                        <br />
                        @if (@product.InStock <= 0)
                        {

                            <a href="#" class="btn btn-primary" disabled>Buy</a>


                        }
                        else
                        {

                            <a asp-controller="WishList" asp-action="AddToWishList" asp-route-id="@product.Id" class="btn btn-danger">Buy</a>

                        }

                    </div>
                </div>

                <br />
            }

        </div>
    </div>
</div>
</div>

LionSkyNot/LionSkyNot/Views/Shop/SaleProducts.cshtml
@model IEnumerable<ProductListViewModel>

 @{
    ViewData["Title"] = "On Sale";
}


<partial name="_ShopPartial" model="@Model"/>

LionSkyNot/LionSkyNot/Views/Shop/ViewDetails.cshtml
@model ProductDetailViewModel

 @{
    ViewData["Title"] = $"{@Model.Name} Details";
}

<link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />


<div class="row">

    <div class="col-sm-3">
        <div class="well">
            <img src="@Model.ImageUrl" class="img-circle" height="100" width="100" alt="Avatar">
        </div>
    </div>
    <div class="col-sm-9">
        <div class="well">
            <p>Name: @Model.Name</p>
            <br />
            <p>Type: @Model.Type</p>
            <br />
            <p style="color:green">Brand: @Model.Brand</p>
            <br />
            @if (@Model.IsOnPromotion)
            {
                <div class="font-size-lg text-danger pt-2"><strike>Old Price: @String.Format(@Model.Price % 1 == 0 ? "{0:0}" : "{0:0.00}", @Model.Price) £ </strike></div>
                <div class="font-size-lg text-warning pt-2"> New Price: @String.Format(@Model.PriceOnPromotion % 1 == 0 ? "{0:0}" : "{0:0.00}", @Model.PriceOnPromotion) £</div>
            }
            else
            {
                <div class="font-size-lg text-danger pt-2">Price: @String.Format(@Model.Price % 1 == 0 ? "{0:0}" : "{0:0.00}", @Model.Price) £</div>
            }
            <br />
            <p style="color:red">Description: @Model.Description</p>
        </div>
    </div>
</div>

LionSkyNot/LionSkyNot/Views/Shop/_ShopPartial.cshtml
@model IEnumerable<ProductListViewModel>

<link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />


<div class="container pb-5 mt-n2 mt-md-n3">
    <div class="row">
        <div class="col-xl-9 col-md-8">

            @if (!Model.Any())
            {
                <div class="container">
                    <div class="jumbotron">
                        <h1>Don't have in the moment products</h1>
                        <p>
                            Please try soon!
                        </p>
                    </div>
                </div>
            }

            @foreach (var product in Model)
            {

                <!-- Item-->
                <div class="d-sm-flex justify-content-between my-4">
                    <div class="media d-block d-sm-flex text-center text-sm-left">
                        <img src="@product.ImageUrl" width="240" height="240">
                        <div class="media-body pt-3">
                            <h3 class="product-card-title font-weight-semibold border-0 pb-0"> <a asp-controller="Shop" asp-action="ViewDetails" asp-route-id="@product.Id">@product.Name</a></h3>
                            <div class="font-size-sm">Brand: @product.Brand</div>
                            <div class="font-size-sm">Type: @product.Type</div>

                            @if (@product.InStock == 0)
                            {
                                <div class="font-size-sm">Soon in stock</div>
                            }
                            else
                            {
                                <div class="font-size-sm">In Stock: @product.InStock</div>
                            }

                            @if (product.IsOnPromotion)
                            {
                                <div class="font-size-lg text-danger pt-2"><strike>Old Price: @String.Format(product.Price % 1 == 0 ? "{0:0}" : "{0:0.00}", product.Price) £ </strike></div>
                                <div class="font-size-lg text-warning pt-2"> New Price: @String.Format(product.PriceOnPromotion % 1 == 0 ? "{0:0}" : "{0:0.00}", product.PriceOnPromotion) £</div>
                            }
                            else
                            {
                                <div class="font-size-lg text-danger pt-2">Price: @String.Format(product.Price % 1 == 0 ? "{0:0}" : "{0:0.00}", product.Price) £</div>
                            }


                        </div>
                    </div>
                    <div class="pt-2 pt-sm-0 pl-sm-3 mx-auto mx-sm-0 text-center text-sm-left" style="max-width: 10rem;">

                        <br />
                        <br />
                        <a asp-controller="Shop" asp-action="ViewDetails" asp-route-id="@product.Id" class="btn btn-warning">View Details</a>


                        <br />
                        <br />
                        @if (@product.InStock <= 0)
                        {

                            <a href="#" class="btn btn-primary" disabled>Buy</a>


                        }
                        else
                        {

                            <a asp-controller="WishList" asp-action="AddToWishList" asp-route-id="@product.Id" class="btn btn-danger">Buy</a>

                        }

                    </div>
                </div>

                <br />
            }

        </div>
    </div>
</div>
</div>