LionSkyNot/LionSkyNot/Areas/Admin/Models/Recipes/RecipeFormModelForAdmin.cs
namespace LionSkyNot.Models.Recipes
{
    public class RecipeFormModelForAdmin
    {
        public int Id { get; set; }

        public string Name { get; set; }

    }
}

LionSkyNot/LionSkyNot/Areas/Admin/Controllers/RecipeController.cs
using LionSkyNot.Controllers;

using LionSkyNot.Models.Recipe;
using LionSkyNot.Models.Recipes;

using LionSkyNot.Services.Recipes;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using static LionSkyNot.Areas.Admin.AdminConstants;


namespace LionSkyNot.Areas.Admin.Controllers
{


    [Area(AreaName)]
    public class RecipeController : BaseController
    {

        private IRecipeService recipeService;

        public RecipeController(IRecipeService recipeService)
        {
            this.recipeService = recipeService;
        }



        [Authorize(Roles = ModeratorAndAdminRole)]
        public IActionResult Successfull()
        {
            return View();
        }


        [Authorize(Roles = AdminRole)]
        public IActionResult ShowRecipes(IEnumerable<RecipeFormModelForAdmin> recipeModel)
        {

            recipeModel = this.recipeService.GetAllRecipesForAdmin();

            return View(recipeModel);

        }


        [Authorize(Roles = ModeratorAndAdminRole)]
        public IActionResult AddRecipe()
        => View();


        [Authorize(Roles = ModeratorAndAdminRole)]
        [HttpPost]
        public async Task<IActionResult> AddRecipe(RecipeFormModel recipeModel)
        {

            if (!ModelState.IsValid)
            {
                return View(recipeModel);
            }

            await this.recipeService.CreateAsync(
                                       recipeModel.Name,
                                       recipeModel.Description,
                                       recipeModel.ImageUrl);


            return RedirectToAction("Successfull");
        }


        [Authorize(Roles = AdminRole)]
        public IActionResult EditRecipe(int id)
        {
            var currentRecipe = this.recipeService.GetRecipeById(id);

            if (currentRecipe == null)
            {
                return BadRequest();
            }


            return View(new RecipeFormModel()
            {
                Name = currentRecipe.Name,
                Description = currentRecipe.Description,
                ImageUrl = currentRecipe.ImageUrl
            });
        }


        [Authorize(Roles = AdminRole)]
        [HttpPost]
        public async Task<IActionResult> EditRecipe(RecipeFormModel recipeModel, int id)
        {

            if (!ModelState.IsValid)
            {
                return View(recipeModel);
            }

            var isEditted = await this.recipeService.EditRecipeAsync(
                                                            id,
                                                            recipeModel.Name,
                                                            recipeModel.ImageUrl,
                                                            recipeModel.Description);

            if (!isEditted)
            {
                return BadRequest();
            }

            return RedirectToAction("Successfull");
        }


        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> DeleteRecipe(int id)
        {
            var isDeleted = await this.recipeService.DeleteAsync(id);

            if (!isDeleted)
            {
                return BadRequest();
            }

            return View("Successfull");
        }
    }
}

LionSkyNot/LionSkyNot/Areas/Admin/Controllers/ShopController.cs
using LionSkyNot.Controllers;

using LionSkyNot.Models.Products;

using LionSkyNot.Services.Products;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using static LionSkyNot.Areas.Admin.AdminConstants;


namespace LionSkyNot.Areas.Admin.Controllers
{
    [Area(AreaName)]
    public class ShopController : BaseController
    {

        private IProductService productService;

        public ShopController(IProductService productService)
        {
            this.productService = productService;
        }



        [Authorize(Roles = ModeratorAndAdminRole)]
        public IActionResult AddProduct()
        {
            return View(new AddProductFormModel()
            {
                Type = this.productService.GetAllTypesProduct(),
                Brand = this.productService.GetAllBrandProduct()
            });

        }


        [Authorize(Roles = ModeratorAndAdminRole)]
        [HttpPost]
        public async Task<IActionResult> AddProduct(AddProductFormModel productModel)
        {

            if (!productService.IsHaveType(productModel.TypeId))
            {
                this.ModelState.AddModelError(nameof(productModel.TypeId), "Don't make some hack tries!");
            }

            if (!productService.IsHaveBrand(productModel.BrandId))
            {
                this.ModelState.AddModelError(nameof(productModel.BrandId), "Don't make some hack tries!");
            }

            if (!ModelState.IsValid)
            {
                productModel.Type = this.productService.GetAllTypesProduct();
                productModel.Brand = this.productService.GetAllBrandProduct();

                return View(productModel);
            }

            await this.productService.CreateProductAsync(
                 productModel.Name,
                 productModel.Price,
                 productModel.InStock,
                 productModel.Description,
                 productModel.ImageUrl,
                 productModel.TypeId,
                 productModel.BrandId);

            return RedirectToAction("Successfull");
        }


        [Authorize(Roles = ModeratorAndAdminRole)]
        public async Task<IActionResult> AddProductsInStock()
        {
            var isDone = await this.productService.UpdateInStockCountOfProductsAsync();

            if (!isDone)
            {
                return RedirectToAction("NotSuccess");
            }


            return View();
        }


        [Authorize(Roles = AdminRole)]
        public IActionResult Successfull()
        {
            return View();
        }


        [Authorize(Roles = AdminRole)]
        public IActionResult NotSuccess()
        {
            return View();
        }


        [Authorize(Roles = AdminRole)]
        public IActionResult ShowProducts(IEnumerable<ProductServiceModel> serviceModel)
        {

            serviceModel = this.productService.GetAllProductsForAdmin();

            return View(serviceModel);
        }


        [Authorize(Roles = AdminRole)]
        public IActionResult EditProduct(int id)
        {

            var currentProduct = this.productService.GetProductById(id);

            if (currentProduct == null)
            {
                return BadRequest();
            }

            return View(new EditProductFormModel()
            {
                ImageUrl = currentProduct.ImageUrl,
                Price = currentProduct.Price,
                Name = currentProduct.Name,
            });
        }


        [Authorize(Roles = AdminRole)]
        [HttpPost]
        public async Task<IActionResult> EditProduct(EditProductFormModel productModel, int id)
        {

            if (!ModelState.IsValid)
            {
                return View(productModel);
            }

            var isEditted = await this.productService.EditProductAsync(
                                                              id,
                                                              productModel.ImageUrl,
                                                              productModel.Name,
                                                              productModel.Price,
                                                              productModel.PromotionPercentage);

            if (!isEditted)
            {
                return BadRequest();
            }

            return RedirectToAction("Successfull");
        }


        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> DeleteProduct(int id)
        {
            var isDeleted = await this.productService.DeleteProductAsync(id);

            if (!isDeleted)
            {
                return BadRequest();
            }

            return View("Successfull");
        }

    }
}

LionSkyNot/LionSkyNot/Controllers/CalculatorController.cs
using LionSkyNot.Models.Calculator;

using LionSkyNot.Views.ViewModels.Calculator;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


namespace LionSkyNot.Controllers
{

    [Authorize]
    public class CalculatorController : BaseController
    {

        public IActionResult Index()
        => View();

        [HttpPost]
        public IActionResult Index(CalculateFormModel calculateModel, CalculatorViewModel model)
        {

            if (!this.ModelState.IsValid)
            {

                return View(calculateModel);

            }

            var calculator = new Calculator();
            model = calculator.Calculation(calculateModel.Goal, calculateModel.Weight);


            return View("Result", model);
        }
    }
}

LionSkyNot/LionSkyNot/Controllers/ClassController.cs
using LionSkyNot.Infrastructure;

using LionSkyNot.Services.Classes;

using LionSkyNot.Views.ViewModels.Classes;

using Microsoft.AspNetCore.Authorization;

using Microsoft.AspNetCore.Mvc;

using Microsoft.Extensions.Caching.Memory;


namespace LionSkyNot.Controllers
{
    public class ClassController : BaseController
    {

        private IClassService classService;
        private IMemoryCache cache;

        public ClassController(IClassService classService, IMemoryCache cache)
        {
            this.classService = classService;
            this.cache = cache;
        }


        public IActionResult Index(AllClassViewModel allClassModel)
        {

            const string allCountOfClassesKeyCache = "AllCountOfClassesKeyCache";

            allClassModel = this.cache.Get<AllClassViewModel>(allCountOfClassesKeyCache);

            if (allClassModel == null)
            {
                allClassModel = this.classService.GetCountOfAllClasses();

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allCountOfClassesKeyCache, allClassModel);
            }


            return View(allClassModel);
        }


        [Authorize]
        public IActionResult ViewAllFitnessClass()
        {

            const string allFitnessClassesKeyCache = "AllFitnessClassesKeyCache";

            var allFitnessClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allFitnessClassesKeyCache);

            if (allFitnessClasses == null)
            {
                allFitnessClasses = this.classService.GetAllClassesByCategorieName("Fitness");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allFitnessClassesKeyCache, allFitnessClasses);
            }


            return View(allFitnessClasses);
        }


        [Authorize]
        public IActionResult ViewAllYogaClass()
        {

            const string allYogaClassesKeyCache = "AllYogaClassesKeyCache";

            var allYogaClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allYogaClassesKeyCache);

            if (allYogaClasses == null)
            {
                allYogaClasses = this.classService.GetAllClassesByCategorieName("Yoga");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allYogaClassesKeyCache, allYogaClasses);
            }


            return View(allYogaClasses);
        }


        [Authorize]
        public IActionResult ViewAllMmaClass()
        {

            const string allMmaClassesKeyCache = "AllMmaClassesKeyCache";

            var allMmaClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allMmaClassesKeyCache);

            if (allMmaClasses == null)
            {
                allMmaClasses = this.classService.GetAllClassesByCategorieName("Mma");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allMmaClassesKeyCache, allMmaClasses);
            }


            return View(allMmaClasses);
        }


        [Authorize]
        public IActionResult ViewAllBoxClass()
        {

            const string allBoxClassesKeyCache = "AllBoxClassesKeyCache";

            var allBoxClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allBoxClassesKeyCache);

            if (allBoxClasses == null)
            {
                allBoxClasses = this.classService.GetAllClassesByCategorieName("Box");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allBoxClassesKeyCache, allBoxClasses);
            }
            return View(allBoxClasses);
        }


        [Authorize]
        public IActionResult ViewAllWrestlingClass()
        {

            const string allWrestlingClassesKeyCache = "AllWrestlingClassesKeyCache";

            var allWrestlingClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allWrestlingClassesKeyCache);

            if (allWrestlingClasses == null)
            {
                allWrestlingClasses = this.classService.GetAllClassesByCategorieName("Wrestling");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allWrestlingClassesKeyCache, allWrestlingClasses);
            }
            return View(allWrestlingClasses);
        }


        [Authorize]
        public IActionResult ViewAllAthleticClass()
        {

            const string allAthleticClassesKeyCache = "AllAthleticClassesKeyCache";

            var allAthleticClasses = this.cache.Get<IEnumerable<ClassViewModel>>(allAthleticClassesKeyCache);

            if (allAthleticClasses == null)
            {
                allAthleticClasses = this.classService.GetAllClassesByCategorieName("Athletic");

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(allAthleticClassesKeyCache, allAthleticClasses);
            }
            return View(allAthleticClasses);
        }


        [Authorize]
        public IActionResult ViewDetails(string id)
        {

            const string viewDetailsKeyCache = "viewDetailsKeyCache";

            var viewDetails = this.cache.Get<ClassDetailsViewModel>(viewDetailsKeyCache);

            if (viewDetails == null)
            {
                viewDetails = this.classService.GetClassForDetails(id);

                var cacheOptions = new MemoryCacheEntryOptions()
                    .SetAbsoluteExpiration(TimeSpan.FromMinutes(15));


                this.cache.Set(viewDetailsKeyCache, viewDetails);
            }
            return View(viewDetails);
        }


        [Authorize]
        public async Task<IActionResult> Join(string id)
        {

            var currentUserId = ClaimsPrincipalExtensions.GetId(this.User);

            if (this.classService.CheckFreePlace(id))
            {
                return View("ToMuchPeopleInClass");
            }

            var result = await this.classService.AddUserToClassAsync(currentUserId, id);

            if (!result)
            {
                return View("UserAlreadyInClass");
            }
            return View("SuccessJoin");
        }


        public IActionResult ViewUserClasses()
        {
            var currentUserId = ClaimsPrincipalExtensions.GetId(this.User);

            return View(this.classService.GetUserClasses(currentUserId));
        }


        public async Task<IActionResult> RemoveFromClassUser(string id)
        {
            var currentUserId = ClaimsPrincipalExtensions.GetId(this.User);

            var result = await this.classService.RemovingClassFromUserAsync(currentUserId, id);

            if (!result)
            {
                return BadRequest();
            }
            return View("SuccessRemoveClassUser");
        }
    }
}

LionSkyNot/LionSkyNot/Controllers/ContactController.cs
using LionSkyNot.Models.Contact;

using Microsoft.AspNetCore.Mvc;
using SendGrid;
using SendGrid.Helpers.Mail;

namespace LionSkyNot.Controllers
{
    public class ContactController : BaseController
    {
        private readonly IConfiguration configuration;

        public ContactController(IConfiguration configuration)
        {
            this.configuration = configuration;
        }


        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(ContactFormModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }
            
            var apiKey = this.configuration["SendGrid:ApiKey"];
            var client = new SendGridClient(apiKey);
            var from = new EmailAddress("rasmuse3@abv.bg", model.Name);
            var subject = model.Subject;
            var to = new EmailAddress("rbbojilov@gmail.com");
            var plainTextContent = "and easy to do anywhere, even with C#";
            var htmlContent = model.Message;
            var msg = MailHelper.CreateSingleEmail(from, to, subject, plainTextContent, htmlContent);
            var response = await client.SendEmailAsync(msg);

            return View("SendSuccess");
        }

    }
}

LionSkyNot/LionSkyNot/Views/Home/AdminPanel.cshtml
<div class="jumbotron text-center">
    <img height = 250 weigth = 250 src="https://st.depositphotos.com/1002881/1285/i/950/depositphotos_12859789-stock-photo-admin-tag.jpg" />
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-1">
            <h3>Menu</h3>
        </div>
    </div>
</div>
<ul class="nav flex-column">
    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Shop
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="AddProduct">Add Product</a>
            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="DeleteProduct">Delete Product</a>
        </div>
    </div>

    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Recipe
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="AddRecipe">Add Recipe</a>
            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="DeleteRecipe">Delete Recipe</a>
        </div>
    </div>

    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Classes
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="AddClass">Add Class</a>
            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="DeleteClass">Delete Class</a>
            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="GetCandidates">Check candidatures</a>
        </div>
    </div>

    <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Exercise
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
             <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="AddExercise">Add exercise</a>
            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="DeleteExercise">Delete exercise</a>
        </div>
    </div>

     <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Fired
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
             <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="FiredTrainer">Fired Trainer</a> 
             <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="FiredCooker">Fired Cooker</a> 
        </div>
    </div>

</ul>

LionSkyNot/LionSkyNot/Views/Home/Contact.cshtml
<!--Section: Contact v.2-->


<div>
    <img src="https://arasturkproperty.com/wp-content/uploads/2022/01/contactus-1.jpg" class="img-fluid" alt="Responsive image">
</div>

<section class="mb-4">

    <!--Section heading-->
    <h2 class="h1-responsive font-weight-bold text-center my-4">Contact us</h2>
    <!--Section description-->
    <p class="text-center w-responsive mx-auto mb-5">Do you have any questions? Please do not hesitate to contact us directly. Our team will come back to you within
        a matter of hours to help you.</p>

    <div class="row">

        <!--Grid column-->
        <div class="col-md-9 mb-md-0 mb-5">
            <form id="contact-form" name="contact-form" action="mail.php" method="POST">

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="name" name="name" class="form-control">
                            <label for="name" class="">Your name</label>
                        </div>
                    </div>
                    <!--Grid column-->

                    <!--Grid column-->
                    <div class="col-md-6">
                        <div class="md-form mb-0">
                            <input type="text" id="email" name="email" class="form-control">
                            <label for="email" class="">Your email</label>
                        </div>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">
                    <div class="col-md-12">
                        <div class="md-form mb-0">
                            <input type="text" id="subject" name="subject" class="form-control">
                            <label for="subject" class="">Subject</label>
                        </div>
                    </div>
                </div>
                <!--Grid row-->

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-md-12">

                        <div class="md-form">
                            <textarea type="text" id="message" name="message" rows="2" class="form-control md-textarea"></textarea>
                            <label for="message">Your message</label>
                        </div>

                    </div>
                </div>
                <!--Grid row-->

            </form>

            <div class="text-center text-md-left">
                <a class="btn btn-primary" onclick="document.getElementById('contact-form').submit();">Send</a>
            </div>
            <div class="status"></div>
        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-3 text-center">
            <ul class="list-unstyled mb-0">
                <li><i class="fas fa-map-marker-alt fa-2x"></i>
                    <p>Sofia, 1000, Bulgaria</p>
                </li>

                <li><i class="fas fa-phone mt-4 fa-2x"></i>
                    <p>Phone: +8888888</p>
                </li>

                <li><i class="fas fa-envelope mt-4 fa-2x"></i>
                    <p>Mail: somemail@abv.bg</p>
                </li>
            </ul>
        </div>
        <!--Grid column-->

    </div>

</section>
<!--Section: Contact v.2-->

LionSkyNot/LionSkyNot/Views/Home/Exercise.cshtml
namespace LionSkyNot.Views.Home
{
    public class Exercise
    {
    }
}

LionSkyNot/LionSkyNot/Views/Home/Index.cshtml
@model IEnumerable<TrainerViewModel>

 @{
    ViewData["Title"] = "Welcome To";
}


<link rel="stylesheet" href="~/css/index.css" asp-append-version="true" />


<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="https://wpstatic.gymbeam.com/blog/wp-content/uploads/mageblog/phil_heath.png" alt="Image">
            <div class="carousel-caption">
                <h3>Join our Classes <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Class")'">NOW</button> </h3>
            </div>
        </div>

        <div class="item">
            <img src="https://static.parade.com/wp-content/uploads/2020/06/iStock-1203599963.jpg" alt="Image">
            <div class="carousel-caption">
                <h1>Eat Healthy !</h1>
                <p>Here you can find our healthy recipes for you and enjoy it!</p>
                <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Index", "Recipe")'">Recipes</button>
            </div>
        </div>

        <div class="item">
            <img src="https://supplementdevil.com/wp-content/uploads/2019/08/phil-heath-launches-his-own-supplement-brand-phil-heath-labs.jpg" alt="Image">
            <div class="carousel-caption">
                <h1>We have a shop for nutritional supplements that you can buy and use it for more POWER and RESULTS !</h1>
                <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "Shop")'">Shop NOW</button>
            </div>
        </div>

        <div class="item">
            <img src="https://images-prod.healthline.com/hlcmsresource/images/AN_images/woman-measuring-stomach-1296x728.jpg" alt="Image">
            <div class="carousel-caption">
                <h1>You don't know how much calories need to eat per day ? Calculate it buy clicking <button type="button" class="btn btn-warning" onclick="location.href='@Url.Action("Index","Calculator")'">HERE</button></h1>

            </div>
        </div>

    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container text-center">
    <h3>What We Do</h3><br>
    <div class="row">
        <div class="col-sm-4">
            <img src="https://i.insider.com/6172edae4f281c001296a1e7?width=700" class="img-responsive" style="width:100%" alt="Image">
        </div>
        <div class="col-sm-4">
            <img src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/a6/4f/49/coffit-club-gym-is-the.jpg?w=500&h=400&s=1" class="img-responsive" style="width:100%" alt="Image">
        </div>
        <div class="col-sm-4">
            <div class="well">
                <p>We offer both group activities and recipes for healthy eating and also the best nutritional supplements</p>
            </div>
            <div class="well">
                <p>Doing this since a lot time , so we know that you will join it ! Just join us don't think it a lot.</p>
            </div>
        </div>
    </div>
</div>
<br>

<br />
<br />

<br />


<h2 style="text-align: center; color:white">These are our best trainers !</h2>
@if (Model.Any(x => x != null))
{
    <div class="container">
        <div class="row">

            @foreach (var trainer in Model)
            {
                <div class="col-sm-4">
                    <div class="panel panel-primary">
                        <div class="panel-heading">@trainer.FullName</div>
                        <div class="panel-body"><img src="@trainer.ImageUrl" class="img-responsive" style="width:100%" alt="Image"></div>
                        <div class="panel-footer">@trainer.Description</div>
                        <div class="panel-footer">@trainer.CategorieName Trainer</div>
                    </div>
                </div>
            }
        </div>
    </div>
}


<div class="row">
    <div class="col-sm-12">
        <div class="panel panel-default text-left">
            <div class="panel-body">
                <p id="statistics-p">Click here to show statistics of this site</p>

                <div class="d-none" id="statistics">
                    <p id="classesCount"></p>
                    <p id="recipeCount"></p>
                    <p id="productCount"></p>
                    <p id="trainerCount"></p>
                    <p id="exerciseCount"></p>
                    <p id="gymClientsCount"></p>
                </div>

                <button type="button" class="btn btn-primary" id="statistics-button">
                    Check
                </button>
            </div>
        </div>
    </div>
</div>


@section Scripts {

<script>
    $('#statistics-button').on('click', ev => {
         $.get('/api/statistics', (data) => {
         $('#classesCount').text("Classes: " + data.classesCount);
         $('#recipeCount').text("Recipes: " + data.recipeCount);
         $('#trainerCount').text("Trainers: " + data.trainerCount );
         $('#exerciseCount').text("Exercises: " + data.exerciseCount );
         $('#productCount').text("Products: " + data.productCount );
         $('#gymClientsCount').text("Gym clients: " + data.gymClientsCount );

         $('#statistics').removeClass('d-none');
         $('#statistics-p').addClass('d-none');
         $('#statistics-button').addClass('d-none');
     })
    });
</script>
}

LionSkyNot/LionSkyNot/Views/Home/Recipe.cshtml
namespace LionSkyNot.Views.Home
{
    public class Reception
    {
    }
}

LionSkyNot/LionSkyNot/Views/Home/Shop.cshtml
namespace LionSkyNot.Views.Home
{
    public class Shop
    {
    }
}